### PR TITLE
Fix 'trying to get property 'id' of non-object"' error on AJAX requests

### PR DESCRIPTION
**Pull request by GiulioPecorella**
Fixes "Trying to get property 'id' of non-object" error on AJAX requests

### CODE REVIEW

**Comment by MWDelaney** [comment]
This makes sense to me, and it's a simple change. Any objections, anyone?

**Comment by mmirus** [comment]
Probably good-to-go, but would like to understand the issue better. @GiulioPecorella do you have an easy example I can reproduce with?

**Comment by mmirus** [comment]
Looping back around here - GTG on my end. Thanks for the PR, @GiulioPecorella!

**Comment by GiulioPecorella** [comment]
Sorry for the late reply guys.

I don't have versions right now but it was Sage 9 + Sage WooCommerce +
Bedrock.
The ecommerce was set up in order to allow orders only for logged in users
and was actually using WooCommerce's One Page Checkout add-on.

As I mentioned, is_admin returns true also for wp_ajax calls so that would
have been a false positive check looking for an admin window on frontend.

Hope I explained it well enough

>

**Comment by mmirus** [comment]
No worries. Mainly, it seemed odd to me that both `get_current_screen()->id === 'woocommerce_page_wc-status'`  and `wp_doing_ajax()` would be true simultaneously, so I wanted to get a closer look at this in action to see when that might be the case (when `! wp_doing_ajax()` would not be redundant).

**Comment by marcelo2605** [comment]
I'm using version 1.0.3 and still getting this error: 

> PHP Notice:  Trying to get property 'id' of non-object in /[...]/vendor/roots/sage-woocommerce/src/woocommerce.php on line 57

Editing the line as this PR suggested solved my problem.

I'm using Ajax Load More plugin.

**Pull request merged**
